# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f117a81fb1bfe0a52a074ebd1bfdc5a97f9ca268164739e457a3024666468a487a110b027d4acafdf39a9d88b2c04ba77af98fe6c7d101366a45ef812a6b80dc

test:
  secret_key_base: 525866f6f27f652e6da8be060288f4adec730818e545ced38520ac9fb427902d46ce77dc7ee1fdfacca81189b476fda5887b9e9022c478b09935f8892dd95a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
